version: '3.8'

services:
  news-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - mongodb
      - clickhouse
    command: >
       node build/index.js

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=mydb
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=mypassword
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  tabix:
    image: spoonest/clickhouse-tabix-web-client:latest
    container_name: tabix
    ports:
      - "8080:8080"
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=mypassword
    depends_on:
      - clickhouse

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0"]
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  clickhouse_data:
  mongo-data:
