version: '3.8'

services:
  news-server:
    build:
      context: . 
      dockerfile: Dockerfile  
    container_name: news  
      - "3000:3000" 
    environment:

      - NODE_ENV=production
    volumes:
      - ./.env:/app/.env 
      - ./build:/app/build  
    restart: unless-stopped 

