name: Biome > Build Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  biome-and-build:
    name: Biome Check and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

      - name: Install dependencies
        run: npm install

      - name: Run Biome lint
        run: npx biome lint

      - name: Fail if lint errors
        if: failure()
        run: exit 1

      - name: Build project
        run: npm run dev
